### ISSUE TITLE
Resolving view models on the go

### ISSUE THREAD

**Issue by Mozart-Alkhateeb** [brianlagunas/xamDockManager-Region-Adapter#1]
I Know this sample is too old but i'm using Infragistics version 19.1.84, The way this sample is created enforces instantiating all views and view models right away. I want to add different types of view to the XamDockManager whenever the user user click the menu button associated with that view, does prism support this ?

**Comment by brianlagunas** [comment]
Of course it does.

**Comment by Mozart-Alkhateeb** [comment]
Yes, I've found a way. Thank you
